import turtle

screen = turtle.Screen()
screen.screensize(canvwidth=500, canvheight=500)
screen.bgcolor("dodgerblue")
t=turtle.Turtle()
t.speed(0)

#intro screen
t.penup()
t.goto(0, 180)
t.pendown()
t.write("My", font=("Arial", 30, "bold"), align="center")

t.penup()
t.goto(0, 0)
t.pendown()
screen.addshape("turtle.gif")
t.shape("turtle.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(-200, 285)
t.pendown()
screen.addshape("ttu.gif")
t.shape("ttu.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(0, -180)
t.pendown()
t.write("Presentation", font=("Arial", 30, "bold"), align="center")

t.penup()
t.goto(225, 360)
t.pendown()
t.fillcolor("red")
t.begin_fill()
for i in range(8):
    t.forward(30)
    t.right(45)
t.end_fill()

t.penup()
t.goto(0,-300)
t.pendown()
t.write("(press enter to continue)", font=("Arial", 15, "bold"), align="center")
nesl = input("Press Enter To Continue: ")
t.clear()

#slide 1
screen.bgcolor("lightsteelblue")
t.penup()
t.goto(0, 250)
t.pendown()
t.write("My Favorite Foods", font=("Arial", 23, "bold"), align="center")

t.penup()
t.goto(0, 185)
t.pendown()
t.write("Burgers, Pizza, and Turtles", font=("Arial", 23, "bold"), align="center")

t.penup()
t.goto(-200, -75)
t.pendown()
screen.addshape("burger.gif")
t.shape("burger.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(25, -75)
t.pendown()
screen.addshape("pizza.gif")
t.shape("pizza.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(250, 300)
t.pendown()
t.fillcolor("red")
t.begin_fill()
t.circle(40)
t.end_fill()

t.penup()
t.goto(0,-300)
t.pendown()
t.write("(press enter to continue)", font=("Arial", 15, "bold"), align="center")
nesl = input("Press Enter To Continue: ")
t.clear()

#slide 2
screen.bgcolor("bisque")
t.penup()
t.goto(0, 250)
t.pendown()
t.write("My Hobbies", font=("Arial", 23, "bold"), align="center")

t.penup()
t.goto(0, 195)
t.pendown()
t.write("Soccer, Listening To Music, Videogames, and Eating", font=("Arial", 18, "bold"), align="center")

t.penup()
t.goto(-200, -75)
t.pendown()
screen.addshape("zyx.gif")
t.shape("zyx.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(65, -75)
t.pendown()
screen.addshape("ball.gif")
t.shape("ball.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(250, 300)
t.pendown()
t.fillcolor("red")
t.begin_fill()
for i in range(4):
    t.forward(40)
    t.left(90)
t.end_fill()

t.penup()
t.goto(0,-300)
t.pendown()
t.write("(press enter to continue)", font=("Arial", 15, "bold"), align="center")
nesl = input("Press Enter To Continue: ")
t.clear()

#slide 3
screen.bgcolor("gray36")
t.penup()
t.goto(0, 250)
t.pendown()
t.pencolor("snow")
t.write("My Favorite Move Is....", font=("Arial", 27, "bold"), align="center")

t.penup()
t.goto(0, 185)
t.pendown()
t.write("Interstellar!", font=("Arial", 27, "bold"), align="center")

t.penup()
t.goto(-200, -75)
t.pendown()
screen.addshape("mov.gif")
t.shape("mov.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(95, -75)
t.pendown()
screen.addshape("inte.gif")
t.shape("inte.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(-280, 300)
t.pendown()
t.fillcolor("red")
t.begin_fill()
for i in range(2):
    t.forward(55)
    t.left(90)
    t.forward(30)
    t.left(90)
t.end_fill()

t.penup()
t.goto(0,-300)
t.pendown()
t.write("(press enter to continue)", font=("Arial", 15, "bold"), align="center")
nesl = input("Press Enter To Continue: ")
t.clear()

#last slide
screen.bgcolor("darkseagreen")
t.penup()
t.goto(0, 250)
t.pendown()
t.pencolor("cornflowerblue")
t.write("My Favorite Sport Is...", font=("Arial", 27, "bold"), align="center")

t.penup()
t.goto(0, 185)
t.pendown()
t.write("Soccer!", font=("Arial", 27, "bold"), align="center")

t.penup()
t.goto(-200, -40)
t.pendown()
screen.addshape("clts.gif")
t.shape("clts.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(90, -40)
t.pendown()
screen.addshape("net.gif")
t.shape("net.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(230, -275)
t.pendown()
t.fillcolor("red")
t.begin_fill()
t.forward(30)
t.goto(230,-240)
t.goto(200,-275)
t.end_fill()

t.penup()
t.goto(0,-300)
t.pendown()
t.write("Slides Finished!", font=("Arial", 25, "bold"), align="center")
nesl = input("press enter to end: ")
t.clear()

screen.bgcolor("black")
t.pencolor("white")
t.penup()
t.goto(0,0)
t.pendown()
t.write("THE END!", font=("Arial", 35, "bold"), align="center")

t.penup()
t.goto(0, -180)
t.pendown()
screen.addshape("taf.gif")
t.shape("taf.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(0, 215)
t.pendown()
screen.addshape("cya.gif")
t.shape("cya.gif")
t.stamp()
t.shape("classic")
print("No More Slides... :(")

turtle.done()